# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, unique=True, verbose_name='phone'),
        ),
        migrations.AlterModelTable(
            name='chargecategory',
            table='ChargeCategory',
        ),
    ]
