# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161213_2045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chargecategory',
            table='finance_chargecategory',
        ),
    ]
