# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161214_1613'),
        ('finance', '0003_auto_20161214_1923'),
    ]

    operations = [
    ]
